import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/componets/Layout";
import profilePic from "../../public/images/profile/developer-pic-3.png";
import Image from "next/image";
import AnimatedText from "@/componets/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/componets/Icons";
import HireMe from "@/componets/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/componets/TransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col-reverse">
            <div className="w-1/2 flex flex-col items-end self-center lg:w-full lg:text-center">
              <AnimatedText
                className="!text-7xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
                text="Turning Vision Into Reality With Code And Design."
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects, showcasing my expertise in web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/BhupendraSinghShahi.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:border-light dark:hover:text-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:recruitbhupendrasinghshahi2023@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="bhupendra"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vh,
                (max-width: 1200px) 50vh,
                50vh"
              />
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute left-8 bottom-8 inline-block w-24 md:hidden">
          <Image
            src={lightBulb}
            alt="Bhupendra"
            className="w-full h-auto"
          ></Image>
        </div>
      </main>
    </>
  );
}
